services:
  postgres:
    image: postgres:16-alpine
    container_name: blog_postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-blog_prod}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - blog_network
  
  blog:
    build: .
    container_name: blog_app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_USERNAME: ${DB_USERNAME:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_HOSTNAME: postgres
      DB_NAME: ${DB_NAME:-blog_prod}
      DB_SSL: "false"
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      PORT: 4000
      MIX_ENV: prod
      PHX_SERVER: "true"
    ports:
      - "${PORT:-4000}:4000"
    volumes:
      - ./priv:/app/priv
    networks:
      - blog_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  blog_network:
    driver: bridge