services:
  app:
    build: .
    image: blog-phoenix
    container_name: blog_app
    ports:
      - "4000:4000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:14-alpine
    container_name: blog_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: