name: Deploy to Home Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Build and Deploy
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env file from GitHub Secrets
        run: |
          echo "DATABASE_URL=ecto://${{ secrets.DB_USERNAME }}:${{ secrets.DB_PASSWORD }}@${{ secrets.DB_HOSTNAME }}/${{ secrets.DB_NAME }}" >> .env
          echo "SECRET_KEY_BASE=${{ secrets.SECRET_KEY_BASE }}" >> .env

      - name: Build and start containers
        run: docker compose up -d --build

      - name: Run Ecto Migrations
        run: |
          sleep 15
          docker compose exec -T app /app/bin/blog eval "Blog.Release.migrate"

      - name: Clean up old Docker images
        run: docker image prune -f
